name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: xcodebuild -workspace syncTunes.xcworkspace/ -scheme SyncTunes -destination 'platform=macOS' clean build test
